In [ ]:
#data structure and data cleaning ,indexig and slicing,data aggregation,data transformation  b

In [2]:
#create pandas 
import pandas as pd

In [6]:
data = [10,True,30,"A"] #using list
series = pd.Series(data)
print(series)

0      10
1    True
2      30
3       A
dtype: object


#data = [1,2,3,4]
i = ['A','B','C','D']
series = pd.Series(data,index=i)
print(series)

In [9]:
data = [1,2,3,4]
i = ['A','B','C','D']
series = pd.Series(data,index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [10]:
#create pandas series using dict
data  = {'a':10,'b':20,'c':50}
series = pd.Series(data)
print(series)

a    10
b    20
c    50
dtype: int64


In [11]:
series.replace(20,100)

a     10
b    100
c     50
dtype: int64

In [15]:
#create series using numpy array
import numpy as np
data = np.array([100,200,300])
series = pd.Series(data,index=['a','d','c','b'])
print(series)

ValueError: Length of values (3) does not match length of index (4)

# #pandas dataframe

In [20]:
#create pandas dataframe from dict of lists
import pandas as pd
data = {'Name':['Alice','Bob','Mary'], 'Age':[23,30,40],'Country':["Usa","Uk","Aus"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   23     Usa
1    Bob   30      Uk
2   Mary   40     Aus


In [27]:
#create 
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns=['A','B','C'])
print(df)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [29]:
#create a dataframe froma nested list
data = [[1,"Alice",25],[2,"Bob",34],[3,"Mary",67]]
print(data)
df = pd.DataFrame(data,columns=["ID","Name","Age"])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 34], [3, 'Mary', 67]]
   ID   Name  Age
0   1  Alice   25
1   2    Bob   34
2   3   Mary   67


In [30]:
#import data ffrom a cssv file and create
iris_df = pd.read_csv("iris_csv")

print(iris_df)

FileNotFoundError: [Errno 2] No such file or directory: 'iris_csv'

In [31]:
iris_df = pd.read_excel("iris_xls")
print(iris_df)

FileNotFoundError: [Errno 2] No such file or directory: 'iris_xls'